### ISSUE TITLE
sgrep cannot identify calls to a static method within the same class

### ISSUE THREAD

**Issue by sjparkinson** [facebook/pfff#128]
I have the following situation:

``` php
class A
{
    public static function methodOne() {}

    public function methodTwo() {
        self::methodOne();
    }
}
```

I was somewhat expecting  `sgrep -e 'A::methodOne()' .` to identify the call to `methodOne` in class A, but it did not.

Is this perhaps something worth implementing?

sgrep version: 0.29

**Comment by aryx** [comment]
It would be nice indeed, but sgrep works mostly at a local syntactical level. To be able to resolve
static calls requires more global analysis, because there could be another file b.php with
class B extends A { .... self::methodOne() }  that actually should also be considered a static call to A::methodOne.
